# Generated by Django 4.2.20 on 2025-03-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('bio', models.TextField()),
                ('languages', models.CharField(max_length=200)),
                ('years_experience', models.PositiveIntegerField()),
                ('contact_number', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('trip_type', models.CharField(choices=[('AD', 'Adventure'), ('BE', 'Beach'), ('CU', 'Cultural'), ('CR', 'Cruise'), ('EC', 'Eco'), ('FD', 'Food & Drink'), ('HI', 'Hiking'), ('SA', 'Safari'), ('SI', 'Sightseeing'), ('SK', 'Ski'), ('WE', 'Wellness')], max_length=2)),
                ('duration', models.PositiveIntegerField(default=1, help_text='Duration in days')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('capacity', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='M', max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='media/trips/')),
            ],
        ),
    ]
